### ISSUE TITLE
点击停止出现错误

### ISSUE THREAD

**Issue by junetwentytwo** [gaodeng/Moon-FM-Support#64]
```
TypeError: Cannot read property 'duration' of undefined
    at a.reportPlayHistory (file:///C:/Program%20Files/WindowsApps/27425IcyArrow.MoonFM-PremiumPodcastApp_1.3.0.0_x64__z9kheaq1rx32y/app/resources/app.asar/dist/electron/renderer.js:76:463378)
    at a.stopPlay (file:///C:/Program%20Files/WindowsApps/27425IcyArrow.MoonFM-PremiumPodcastApp_1.3.0.0_x64__z9kheaq1rx32y/app/resources/app.asar/dist/electron/renderer.js:76:462415)
    at click (file:///C:/Program%20Files/WindowsApps/27425IcyArrow.MoonFM-PremiumPodcastApp_1.3.0.0_x64__z9kheaq1rx32y/app/resources/app.asar/dist/electron/renderer.js:76:465286)
    at W (file:///C:/Program%20Files/WindowsApps/27425IcyArrow.MoonFM-PremiumPodcastApp_1.3.0.0_x64__z9kheaq1rx32y/app/resources/app.asar/dist/electron/renderer.js:2:17939)
    at HTMLDivElement.i (file:///C:/Program%20Files/WindowsApps/27425IcyArrow.MoonFM-PremiumPodcastApp_1.3.0.0_x64__z9kheaq1rx32y/app/resources/app.asar/dist/electron/renderer.js:2:18920)
    at HTMLDivElement.Gt.r._wrapper (file:///C:/Program%20Files/WindowsApps/27425IcyArrow.MoonFM-PremiumPodcastApp_1.3.0.0_x64__z9kheaq1rx32y/app/resources/app.asar/dist/electron/renderer.js:2:40526)
```

---

Moon FM 1.3.0
Electron 5.0.8
win32 10.0.18362
Locale: zh-CN

**Comment by gaodeng** [comment]
新版本应该已修复
