### ISSUE TITLE
在后台不播放时稳定闪退

### ISSUE THREAD

**Issue by senventise** [gaodeng/Moon-FM-Support#75]
软件在后台时在通知栏里暂停播放，十几秒后崩溃，百分之百复现，以前的版本没有这个问题，最近才开始的。

软件版本：1.9.27
系统： Android P
错误日志：
```
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=fm.moon.app/com.guichaguri.trackplayer.service.MusicService }: app is in background uid UidRecord{910bcba u0a4 SVC  bg:+1m0s614ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
	at android.app.ContextImpl.startService(ContextImpl.java:1532)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at com.guichaguri.trackplayer.module.MusicModule.waitForConnection(MusicModule.java:111)
	at com.guichaguri.trackplayer.module.MusicModule.getPosition(MusicModule.java:459)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
	at android.os.Looper.loop(Looper.java:193)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by gaodeng** [comment]
🙏  多谢反馈，新版本已修复。
